version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mg
    ports:
      - 27019:27017
    volumes:
      - ./MongoDB:/data/db
    
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - 8001:8001
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend